config/routes.rb
SampleAppForRails::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers, :microposts
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  
  match '/signout', :to => 'sessions#destroy'
  match '/signin', :to => 'sessions#new'

  match '/home', :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'

  match '/signup', :to => 'users#new'
  
  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
				<li><a href="http://news.railstutorial.org/">News</a></li>
				<li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
		</ul>
	</nav>
</footer>	

app/views/layouts/_header.html.erb
<header>
<%= link_to logo, root_path %>
<nav class="round">
<ul>
		<li><%= link_to "Home", home_path %></li>
		<% if signed_in? %>
				<li><%= link_to "Profile", user_path(current_user) %></li>
				<li><%= link_to "Users", users_path %></li>
				<li><%= link_to "Settings", edit_user_path(current_user) %></li>
		<% end %>
		<li><%= link_to "Help", help_path %></li>
		<% if signed_in? %>
				<li><%= link_to "Sign out", signout_path %></li>
		<% else %>
				<li><%= link_to "Sign in", signin_path %></li>
		<% end %>
</ul>
</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    "application" %>

app/views/layouts/application.html.erb
<DOCTYPE html>
<html>
		<head>
				<title><%= title %></title>
				<%= csrf_meta_tags %>
				<%= javascript_include_tag "application" %>
				<%= render 'layouts/stylesheets' %>
		</head>
		<body>
				<div class="container">
            <%= render 'layouts/header' %><br />
						<section class="round">
						<% flash.each do |key, value| %>
								<%= content_tag(:div, value, :class => "flash #{key}") %>
						<% end %>
							<%= yield %>
						</section>
            <%= render 'layouts/footer' %><br />
						<%= debug(params) if Rails.env.development? %>
				</div>
		</body>
</html>